apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    name: nginx
spec:
  replicas: 1
  selector:
    name: nginx
  template:
    metadata:
      name: nginx-rc
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: gcr.io/aerobic-furnace-111811/nginx-personal-server:v0.17
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
          - containerPort: 443
        volumeMounts: 
          - name: "rahhal"
            mountPath: "/etc/secrets/rahh.al"
            readOnly: true
          - name: "onrush"
            mountPath: "/etc/secrets/onru.sh"
            readOnly: true
      volumes:
        - name: "rahhal"
          secret: 
            secretName: "rahh.al"
        - name: "onrush"
          secret: 
            secretName: "onru.sh"
