apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    name: nginx
    role: cert-app
spec:
  replicas: 1
  selector:
    name: nginx
    role: cert-app
  template:
    metadata:
      name: nginx-rc
      labels:
        name: nginx
        role: cert-app
    spec:
      containers:
      - name: nginx
        image: ployst/letsencrypt:0.0.5
        env:
        - name: EMAIL
          value: <email address>
        - name: DOMAINS
          value: <domain>
        - name: RC_NAMES
          value: <rc name>
        ports:
        - name: ssl-proxy-http
          containerPort: 80
