apiVersion: v1
kind: Service
metadata:
  name: nginx-external
  labels:
    name: nginx-external
spec:
  type: LoadBalancer
  loadBalancerIP: 104.197.4.90
  ports: 
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: http-syncthing
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    name: nginx
