apiVersion: v1
kind: ReplicationController
metadata:
  name: owncloud-rc
  labels:
    name: owncloud
spec:
  replicas: 1
  selector:
    name: owncloud
  template:
    metadata:
      name: owncloud-rc
      labels:
        name: owncloud
    spec:
      containers:
      - name: owncloud
        image: gcr.io/aerobic-furnace-111811/owncloud-personal-server:v0.11
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        volumeMounts:
            # This name must match the volumes.name below.
          - name: persistent-storage
            # Mount path within the container.
            mountPath: /var/www/html
      - name: syncthing
        image: gcr.io/aerobic-furnace-111811/syncthing-personal-server:v0.5
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
          - containerPort: 22000
          - containerPort: 21025
            protocol: UDP
        volumeMounts:
          - name: persistent-storage
            mountPath: /var/www/html
      volumes:
        - name: persistent-storage
          gcePersistentDisk:
            # This disk must already exist.
            pdName: owncloud-disk
            fsType: ext4
