apiVersion: v1
kind: Service
metadata:
  name: owncloud-frontend
  labels:
    name: owncloud-frontend
spec:
  type: LoadBalancer
  ports: 
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: owncloud
