apiVersion: v1
kind: Pod
metadata:
  name: owncloud
  labels:
    name: owncloud
spec:
  containers:
  - name: owncloud
    image: owncloud:8.2-apache
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 80
    volumeMounts:
        # This name must match the volumes.name below.
      - name: owncloud-persistent-storage
        # Mount path within the container.
        mountPath: /var/www/html
  volumes:
    - name: owncloud-persistent-storage
      gcePersistentDisk:
        # This disk must already exist.
        pdName: owncloud-disk
        fsType: ext4
