apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  containers:
  - name: postgres
    image: postgres:9.5
    imagePullPolicy: IfNotPresent
    env:
     - name: PGDATA
       value: /var/lib/postgresql/data/pgdata
    ports:
      - containerPort: 5432
    volumeMounts:
      # This name must match the volumes.name below.
      - name: postgres-persistent-storage
        # Mount path within the container.
        mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-persistent-storage
      gcePersistentDisk:
        # This disk must already exist.
        pdName: postgres-disk
        fsType: ext4
