apiVersion: v1
kind: Service
metadata:
  name: syncthing-external
  labels:
    name: syncthing-external
spec:
  type: LoadBalancer
  loadBalancerIP: 104.197.4.90
  ports: 
    - name: syncthing
      port: 22000
      targetPort: 22000
      protocol: TCP
  selector:
    name: owncloud
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-external-udp
  labels:
    name: syncthing-external-udp
spec:
  type: LoadBalancer
  loadBalancerIP: 104.197.4.90
  ports: 
    - name: syncthing-udp
      port: 21025
      targetPort: 21025
      protocol: UDP
  selector:
    name: owncloud
