apiVersion: v1
kind: Service
metadata:
  name: syncthing-service
  labels:
    name: syncthing-service
spec:
  ports: 
    - port: 8080
      targetPort: 8080
      name: http
    - port: 22000
      targetPort: 22000
      name: syncthing
    - port: 21025
      targetPort: 21025
      protocol: UDP
      name: syncthing-udp
  selector:
    name: owncloud
